Repository Rassey/Skidor, pull requests merged in 2022-01, with the labels that each got.

#15 fixa söka efter åkaren medan/efter loppet, fixat difftiderna
  src/com/yajava/Data/AkarList.java
  src/com/yajava/Data/SokAkare.java
  src/com/yajava/Data/Sortering.java
  src/com/yajava/Utskrifter/MenyerSkrivare.java
  src/com/yajava/Utskrifter/OtherPrintOut.java
  src/com/yajava/Utskrifter/PrintOut.java
  src/com/yajava/akare/Akare.java
  src/com/yajava/akare/ToStringHantering.java
  src/com/yajava/app/Main.java
  src/com/yajava/berakning/IndividuellLogik.java
  src/com/yajava/berakning/TidRaknare.java
  src/com/yajava/menyer/MenyInnanStartLogik.java
  src/com/yajava/menyer/StartMenyLogik.java
Labels: enhancement

#17 fixade till README filen
  README.md
  img/Alex.png
  img/Andreas.png
  img/Anna.png
  img/Mohamad.png
  img/preview.gif
Labels: Readme File update

#18 refactor, mm
  src/com/yajava/Data/SokAkare.java
  src/com/yajava/Utskrifter/PrintOut.java
  src/com/yajava/akare/Akare.java
  src/com/yajava/berakning/IndividuellLogik.java
  src/com/yajava/berakning/TidGenerator.java
  src/com/yajava/input/InputSafety.java
  src/com/yajava/menyer/MenyInnanStartLogik.java
  src/com/yajava/menyer/StartMenyLogik.java
Labels: Final Touches
